### ISSUE TITLE
How do I pass context?

### ISSUE THREAD

**Issue by mwethington** [alt-j/fast-react-server#20]
How do I do the following with fast-react-server?

When I tried converting it I keep getting null context.

Old version:

const React = require('react');
const ReactDOMServer = require('react-dom/server');
const serverSide = require('./serverSideRender');
const Components = serverSide.components;

exports.render = render;

function render(component, model, onComplete) {
        const chunks = component.split('.');
        var componentToRender = Components;
        chunks.forEach((ele) => {
                componentToRender = componentToRender[ele];
        });

        const element = React.createFactory(componentToRender)(model);
        const result = ReactDOMServer.renderToString(element);

    onComplete(null, result);
}

New version:

const React = require('fast-react-server');
const ReactRender = require('fast-react-render');
const serverSide = require('./serverSideRender');
const Components = serverSide.components;

exports.render = render;

function render(component, model, onComplete) {
        const chunks = component.split('.');
        var componentToRender = Components;
        chunks.forEach((ele) => {
                componentToRender = componentToRender[ele];
        });

        const element = React.createElement(componentToRender, model);
        var result = ReactRender.elementToString(element);

    onComplete(null, result);
}

**Comment by alt-j** [comment]
I see you have a require the module `require('./serverSideRender')`, please, check that declarations of all your modules used `fast-react-server` instead of `react`.

**Comment by alt-j** [comment]
If your problem isn't solved, then reopen pr.

**Comment by mwethington** [comment]
Hmmm..

import React from 'react';

Would you change that to 

import React from 'fast-react-server'; ?

Also, a dev said he prefers this syntax versus CreateElement...

const element = React.createFactory(componentToRender)(model);

Since it does not use createElement() which I think may be an issue.

**Comment by alt-j** [comment]
You can see, how we do it in the [seed](https://github.com/alt-j/fast-react-seed).
