### ISSUE TITLE
isValidElement

### ISSUE THREAD

**Issue by KlonD90** [alt-j/fast-react-server#21]
This method not implemented.
Some popular modules use it like a react router.
How can i make some things for pass through it?

**Comment by alt-j** [comment]
Yes, today this method doesn't implemented yet. We need to implement it.
Do you want to try do it?

**Comment by KlonD90** [comment]
In process. But it's hard so i don't know in results.

**Comment by alt-j** [comment]
I think, we can add simple variant with only two checks:
- object has not empty property `type`,
- object has property `props`, which is object

**Comment by KlonD90** [comment]
Ok. That's enough in my case.

**Comment by KlonD90** [comment]
Can you make a release with this stuff?

I need this features in production ._.

**Comment by alt-j** [comment]
Yes, of course)

**Comment by alt-j** [comment]
@KlonD90 1.4.0
